source 'https://github.com/CocoaPods/Specs.git'

target 'Sample' do
  platform :ios, '9.0'
  use_frameworks!

  pod 'TIFeedParser', :path => '../'
  pod 'Alamofire'

  target 'SampleTests' do
    inherit! :search_paths
  end
end
